#tell travis that super use permission is needed
sudo: required
#tell travis that we need docker image being installed. 
#travis will auto install a copy of docker to running container
services:
  - docker

#steps before test run
before_install:
#-t <tag_name>: create tag instead of using container id that we don't know.
#this tag will be only used for this process
  - docker build -t docker-react -f Dockerfile.dev .

#set of commands to run test
script:

  - docker run -e CI=true docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  #environment name in elasticbeanstalk
  env: "Dockerreact-env"
  #S3 bucket name. travis will put zip file to here
  bucket_name: "elasticbeanstalk-us-east-1-171406177921"
  #same as app name
  bucket_path: "docker-react"
  #only deploy code when master repository is changed.
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
  #make sure put double quote around
    secure: "$AWS_SECRET_KEY"
